### PR TITLE
Drop support for Austin lab

### PR DESCRIPTION
**Pull request by danrue**
- Drop "-K" (sudo password) from Makefile - it was only necessary for
  Austin (qa-pxe host).
- Drop local/roles/erp-provision-austin-host.
- Update Linaro.erp-run-test-suite to 1.4.0 to pick up plan overlay
  support.
- In hosts, drop open estuary hosts - they're not used.
- In hosts, drop austin hosts - they're no longer available.

Signed-off-by: Dan Rue <dan.rue@linaro.org>

### CODE REVIEW

**Comment by danrue** [comment]
@chase-qi please review (why don't you show up in reviewers list?!)

**Comment by chase-qi** [comment]
@danrue I guess you need to add me to collabrator list(repo -> settings -> collaborators & team) so that I can receive notifications on the repo.

I tried to add you to https://github.com/Linaro/libhugetlbfs, you should have received email from github.

**Comment by fboudra** [comment]
@danrue it was due to the lack of permissions for the QA team on this repo. It's now resolved.

**Comment by chase-qi** [comment]
@fboudra Thanks a lot!

**Pull request merged**
